app/controllers/v1/runs_controller.rb, spec/requests/v1/runs_spec.rb
Needed for https://github.com/sanger/traction-ui/pull/68/files
=> Permit updating run name 

app/controllers/v1/libraries_controller.rb, app/controllers/v1/runs_controller.rb, app/messages/messages.rb, app/messages/messages/message.rb, app/pipelines/pipelines.rb, app/pipelines/pipelines/configuration.rb, app/resources/v1/library_resource.rb, app/resources/v1/run_resource.rb, config/initializers/pipelines.rb, spec/factories/flowcell.rb, spec/messages/message_spec.rb, spec/messages/messages_spec.rb, spec/pipelines/configuration_spec.rb, spec/pipelines/pipelines_spec.rb
Pipeline configuration created in initializer.
For example in the console type Pipelines.saphyr and bingo!
=> pipelines configuration will now be loaded on application startup.

db/migrate/20190115144439_create_libraries.rb, db/migrate/20190212101519_create_flowcells.rb, db/migrate/20190212111752_create_runs.rb, db/migrate/20190523071418_add_foreign_keys.rb, db/schema.rb, lib/tasks/create_dummy_runs.rake
Moved foreign key creation to last migration.
=> Fixes #38.

app/csv_generator/csv_generator.rb, app/resources/v1/pacbio/run_resource.rb, spec/csv_generator/csv_generator_spec.rb, spec/models/pacbio/run_spec.rb, spec/requests/v1/pacbio/runs_spec.rb
Refactored the CSVGenerator
Added created_at to the pacbio run resource
Required changes for Tracion UI GPL-073-sample-sheet-generation branch
=> Support for downloading a PacbioRun Sample Sheet CSV

app/models/pacbio/well.rb, config/pipelines.yml, spec/models/pacbio/well_spec.rb, spec/requests/v1/pacbio/wells_spec.rb
Changed the pipelines.yml config to call position_leading_zero
method, instead of position, as this was having rippling effects
=> Sample Sheet leading zero

app/controllers/v1/pacbio/wells_controller.rb, app/models/pacbio/well_factory.rb, spec/factories/pacbio/request_library.rb, spec/factories/pacbio/wells.rb, spec/models/pacbio/well_factory_spec.rb, spec/requests/v1/pacbio/wells_spec.rb
Added lots of tests
Removed validation that libraries have to exist,
as libraries might be an empty list
=> Fix removing libraries from a well

config/routes.rb, spec/requests/v1/pacbio/libraries_spec.rb
=> Refactored jsonapi routes for pacbio libraries

.rubocop.yml, config/pipelines.yml, spec/pipelines/pacbio/message_spec.rb
Change event to send name rather than id to warehouse
- also change namespace of cop to please rubocop
=> GPL-264 send name not id of run to warehouse

app/models/pacbio/library_factory.rb, spec/models/pacbio/library_factory_spec.rb
=> Added validation for cost code on library creation

README.md, lib/tasks/create_enzymes.rake, lib/tasks/create_tags.rake, lib/tasks/pacbio_runs.rake, lib/tasks/saphyr_runs.rake
=> Issue248 raketask

config/initializers/date_and_time_formats.rb, spec/requests/v1/tag_sets_spec.rb
debugging line removed from test
=> Changed date format to have 24 hour time (opposed to 12 hour)

app/controllers/v1/pacbio/libraries_controller.rb, config/routes.rb
needed for issue 347 PR in traction UI
=> issue 347 in traction UI edit libraries

config/environments/development.rb
cors config never updated for library deletion locally
=> allow devs to delete libraries locally

lib/tasks/create_tags.rake, lib/tasks/ont_runs.rake, lib/traction_graphql.rb
Use the pcr_tag_set_name from the config in the rake tasks
=> Use pcr_tag_set_name from config in rake tasks

app/graphql/types/outputs/ont/flowcell_type.rb, app/graphql/types/query_types.rb, spec/requests/v2/ont/libraries_spec.rb, spec/requests/v2/ont/runs_spec.rb
Part of #215
* Add a filter spec for libraries endpoint.
* Add an ont_runs endpoint for getting all runs.
* Add an ont_run endpoint for getting a single run by ID
=> GPL-387: Update GraphQL queries

.rubocop.yml
=> Turn on inspections in Rubocop

README.md
* Update the README to make it easier for new developers to set up RabbitMQ
=> Add instructions for declaring the RabbitMQ exchange

README.md, app/graphql/mutations/base_covid_run_mutation.rb, app/graphql/mutations/create_covid_run_mutation.rb, app/graphql/mutations/update_covid_run_mutation.rb, spec/requests/v2/ont/runs_spec.rb
Closes #317
* Fixes from previous pull request
=> GPL-388: Update runs mutation spec and behaviour

.gitignore, .travis.yml, README.md, app/graphql/mutations/base_covid_run_mutation.rb, app/models/ont/flowcell.rb, app/models/ont/request_factory.rb, app/models/ont/run.rb, app/pipelines/pipelines/constants_accessor.rb, config/application.rb, config/env_constants.yml.example, config/pipelines.yml, lib/tasks/create_tags.rake, lib/tasks/ont_data.rake, lib/traction_graphql.rb, spec/factories/ont/libraries.rb, spec/models/ont/flowcell_spec.rb, spec/models/ont/request_factory_spec.rb, spec/models/ont/run_spec.rb, spec/pipelines/constants_accessor_spec.rb, spec/pipelines/ont/message_spec.rb, spec/requests/v2/ont/runs_spec.rb
Closes #394
* Add new separate environment constants YAML file for environment specific values.
* Set up nested message creation for Ont Runs (one message per entire run).
* Update tests for new expectations from ConstantsAccessor.
=> Update study UUID

app/controllers/v1/pacbio/runs_controller.rb, spec/requests/v1/pacbio/runs_spec.rb
*Remove name from pacbio run parameters since it is now auto generated
=> removed run name from pacbio request params

app/models/pacbio/plate.rb, app/models/pacbio/run.rb, app/models/pacbio/well.rb, app/resources/v1/pacbio/run_resource.rb, spec/models/pacbio/plate_spec.rb, spec/models/pacbio/well_spec.rb, spec/requests/v1/pacbio/runs_spec.rb
=> Generate sample sheet broken in uat

config/pipelines.yml, spec/pipelines/ont/message_spec.rb
=> modified tag identifier to be group id.

app/resources/v1/saphyr/container_material_resource.rb
Subpart of https://github.com/sanger/traction-ui/issues/413  
Coupled with https://github.com/sanger/traction-ui/pull/488
=> Return the material_id of the container_material in resource

spec/factories/saphyr/chips.rb, spec/factories/saphyr/flowcell.rb, spec/requests/v1/saphyr/runs_spec.rb
=> Minor test for Saphyr run data 

.rubocop.yml, README.md, app/models/ont/add_tags.rb, config/puma.rb, lib/tasks/create_tags.rake, spec/factories/plates.rb, spec/models/ont/add_tags_spec.rb
=> Reorder ont tags

.release-version
Closes #
*Bumped release version
*
* ...
=> Develop into master

app/models/well.rb, app/resources/v1/pacbio/well_resource.rb, spec/requests/v1/pacbio/plates_spec.rb
=> Add request to pacbio well resource

.github/workflows/asset_dispatch.yml, .github/workflows/automated_release_and_build.yml, .github/workflows/check_release_version.yml
Part of https://github.com/sanger/deployment/issues/71
=> DPL-083 Improve workflows in GitHub to better support release versioning

app/csv_generator/csv_generator.rb, spec/csv_generator/csv_generator_spec.rb
Wells are now sorted by column for sample sheet generation in pacbio runs
Closes #647 
*
*
* ...
=> DPL-136 sample sheet well order for pacbio runs 

lib/tasks/create_tags.rake
Closes #556
* Remove addition of `increment_oligo!` to string
* Simplify tag creation slightly
* Add new tag set
=> Issue556/gpl 991 as a long read user {craig} i need a new tag group for bacterial multiplexing

app/controllers/v1/pacbio/plates_controller.rb, app/models/pacbio/plate_creator.rb, app/pacbio/pacbio.rb, config/pipelines.yml
Closes #639
* Add library type to flowcell message
Dependent on: https://github.com/sanger/unified_warehouse/pull/314 being released before this.
=> Issue639/dpl 124 add the concept of library type to a request {c m v 4}

app/models/container_material.rb, app/pipelines/pipelines/requestor/factory.rb
=> Improve tube import

lib/tasks/create_tags.rake
=> Added new tag groups.

config/pipelines.yml
=> Modified sample sheet headers for adaptive loading.

app/resources/v1/pacbio/library_resource.rb, app/resources/v1/pacbio/pool_resource.rb, app/resources/v1/shared/run_suitability.rb
Picked up in code review by @stevieing but apparantly causing actual problems loading the server in UAT. So cherrypicking this from my other branch.
=> Fix shared runsuitability namespace

config/routes.rb
=> Use cookie not pool

config/routes.rb
=> Add secret to session cookie

app/resources/v1/pacbio/request_resource.rb
=> Hotfix resource loading

app/resources/v1/pacbio/well_resource.rb
Figured out what was wrong on the nursery drop off, so got the fix in case you need it on Monday.
=> Fix plate on wells

lib/tasks/create_library_types.rake
=> Add saphyr library type

README.md, app/controllers/v1/ont/requests_controller.rb, app/models/plate.rb, app/ont/ont.rb, app/resources/v1/ont/request_resource.rb, config/routes.rb, lib/tasks/ont_data.rake, spec/lib/tasks_spec.rb, spec/models/reception/resource_factory_spec.rb, spec/requests/v1/ont/requests_spec.rb
=> Add ont request resource endpoints

app/models/pacbio/run.rb, app/models/pacbio/smrt_link_version_type.rb, config/initializers/types.rb
=> Added custom type for smrt link version.

config/pacbio_smrt_link_versions.yml, config/pipelines.yml, spec/pipelines/pacbio/sample_sheet_spec.rb
=> Modified smrt link comulmn name and sample sheet heading.

lib/tasks/create_tags.rake, spec/lib/tasks_spec.rb
=> Added new pacbio tag set.

app/resources/v1/ont/library_resource.rb, app/resources/v1/ont/pool_resource.rb, db/seeds.rb, spec/requests/v1/ont/libraries_spec.rb, spec/requests/v1/ont/pools_spec.rb
Updates to the previously merged DPL-279 work for ONT pooling and libraries
Minor changes to data callable through the ont API
Updated db seed data
=> DPL-279 updates

lib/tasks/create_qc_assay_types.rake
Add unit to QcAssayType rake task.
Todo:
On deployment, run rake task
=> Add unit to QcAssayTypes

app/resources/v1/ont/pool_resource.rb, app/resources/v1/ont/request_resource.rb, config/initializers/jsonapi_resources.rb, spec/requests/v1/ont/pools_spec.rb, spec/requests/v1/ont/requests_spec.rb
* Added source_identifier filter to ont requestes endpoint
* Changed max page number to 1000 to accomodate filters with large results
=> DPL-279 Post UAT fixes

app/models/tube.rb, app/resources/v1/ont/pool_resource.rb, app/resources/v1/pacbio/library_resource.rb, app/resources/v1/pacbio/plate_resource.rb, app/resources/v1/pacbio/pool_resource.rb, app/resources/v1/pacbio/request_resource.rb, app/resources/v1/pacbio/run_resource.rb, spec/requests/v1/ont/pools_spec.rb, spec/requests/v1/ont/requests_spec.rb, spec/requests/v1/pacbio/libraries_spec.rb, spec/requests/v1/pacbio/plates_spec.rb, spec/requests/v1/pacbio/pools_spec.rb, spec/requests/v1/pacbio/requests_spec.rb, spec/requests/v1/pacbio/runs_spec.rb
Added pagination to pacbio resources. This includes select filters for each resource
=> DPL-594 - Pacbio resources pagination support

app/resources/v1/ont/pool_resource.rb, app/resources/v1/ont/request_resource.rb, app/resources/v1/pacbio/library_resource.rb, app/resources/v1/pacbio/pool_resource.rb, app/resources/v1/pacbio/request_resource.rb
Closes #
* enabled pools resource to be filtered by sample name
*
* ...
=> DPL-594 - Pacbio pagination post uat fixes 

db/migrate/20230207105823_change_pacbio_run_comments_limit.rb, db/schema.rb, spec/models/pacbio/run_spec.rb
=> Increase pacbio run comments limit

app/resources/v1/pacbio/library_resource.rb, spec/requests/v1/pacbio/libraries_spec.rb
Added ability to search library source_identifier by the plate:well format
Closes #952
=> DPl-693 - Search pacbio libraries by source_identifier in the format plate:well

app/models/pacbio/smrt_link_version.rb, app/support/version.rb, config/pacbio_smrt_link_versions.yml, spec/lib/tasks_spec.rb, spec/models/pacbio/smrt_link_version_spec.rb
=> 962 dpl 706 as developers we need to create a smrt link version 12 for revio so that users can create sample sheets

config/pacbio_smrt_link_versions.yml, spec/requests/v1/pacbio/runs_spec.rb
=> Modified polymerase kit to be a string.

config/pipelines/pacbio.yml, spec/pipelines/pacbio/sample_sheet_spec.rb
=> Fixed library_type error for SMRT Link 12 sample sheet.

config/pipelines/pacbio.yml, spec/pipelines/pacbio/sample_sheet_spec.rb
=> Bug fix fix reagent plate smrt link 12 sample sheet error

config/pipelines/pacbio.yml, spec/pipelines/pacbio/sample_sheet_spec.rb
=> deleted skbb from plate 2, added reagent plate on sample level

app/models/pacbio/run.rb, app/validators/well_position_validator.rb, spec/models/pacbio/run_spec.rb, spec/validators/well_position_validator_spec.rb
=> Added well position validator.

app/validators/well_position_validator.rb, spec/validators/well_position_validator_spec.rb
=> Added fix for well position validator when there are no wells.

app/validators/well_position_validator.rb, spec/validators/well_position_validator_spec.rb
=> Added fix for partial plates for revio runs.

app/models/concerns/dual_sourced_pool.rb, app/models/ont/pool.rb, app/models/pacbio/pool.rb, spec/models/concerns/dual_sourced_pool_spec.rb
Updated pool source identifier by changing source concern to also include source tubes
=> Pool source identifier update

config/pipelines/pacbio.yml, spec/pipelines/pacbio/message_spec.rb
Closes #990 
* Added pacbio library tube barcode to pacbio warehouse message
* Removed plate_barcode from pacbio warehouse message
=> DPL-741 - Add pac_bio_library_tube_barcode to mlwh message

config/application.rb, spec/models/pacbio/request_spec.rb
Updated pacbio default cost code as requested by stakeholders
=> Updated pacbio default cost code

.github/workflows/ruby.yml, README.md
=> Updated mysql version to 8.0

app/resources/v1/reception_resource.rb, config/pipelines/reception.yml, db/migrate/20230914111434_add_public_name_to_sample.rb, db/schema.rb, spec/factories/samples.rb, spec/requests/v1/reception_spec.rb
=> DPL754 Add public name to sample and write it in the warehouse

app/models/aliquot.rb, app/models/pacbio/request.rb, lib/tasks/migrate_pacbio_aliquot_data.rake, spec/lib/tasks/migrate_pacbio_aliquot_data.rake_spec.rb, spec/models/aliquot_spec.rb, spec/models/pacbio/request_spec.rb, spec/models/reception/resource_factory_v1_spec.rb, spec/models/reception/resource_factory_v2_spec.rb
Closes #1159
- Adds rake task to add primary aliquots to requests
- Adds aliquotable concern to requests
- Adds conditional to volume, concentration, template_prep_kit_box_barcode and insert_size presence validation on aliquot to not run for Pacbio::Request aliquots.
=> DPL-1000 - Support pacbio request aliquots

config/pacbio_smrt_link_versions.yml, config/pipelines/pacbio.yml, lib/tasks/pacbio_data.rake, spec/exchanges/run_csv/pacbio_sample_sheet_spec.rb, spec/lib/tasks/pacbio_data.rake_spec.rb, spec/models/pacbio/run_spec.rb, spec/requests/v1/pacbio/runs_spec.rb
Closes #1177 
- Adds v13 revio support (using old sample sheet format)
Relies on UI branch: https://github.com/sanger/traction-ui/pull/1519
=> DPL-1039 - Support SMRTLink v13

config/pipelines/pacbio.yml, spec/exchanges/run_csv/pacbio_sample_sheet_spec.rb
- Adds 'Use Adaptive Loading' column to v13 Revio sheets with a default value of 'FALSE'
=> PacBio SMRTLink v13 support - Adds 'Use Adaptive Loading' to Revio sheets

app/resources/v1/pacbio/runs/library_pool_resource.rb, spec/requests/v1/pacbio/runs/wells_spec.rb
- Fixes library run resource and adds test coverage for issue.
=> Fix - LibraryPool Run resource fix

README.md, bin/setup, db/migrate/20240219180656_create_cost_code_and_study_report_view.rb, db/schema.rb, db/seeds.rb, lib/tasks/tol_tubes_report_view.rake, spec/lib/tasks/tol_tubes_report_view_spec.rb
Closes #1217 
- Add a view to access the data Alice needs.
=> DPL-1094 Cost code and study report view

app/models/concerns/aliquotable.rb, app/models/pacbio/pool.rb, lib/tasks/migrate_pacbio_aliquot_data.rake, spec/lib/tasks/migrate_pacbio_aliquot_data.rake_spec.rb, spec/requests/v1/pacbio/pools_spec.rb
Closes #
- enforces used_aliquots have a 'derived' aliquot_type
- fixes pool defaults for missing required values in aliquot data migration
=> DPL-989 - UAT fixes

app/models/pacbio/well.rb
- Fixes bug where pool_ids and library_ids received as strings were breaking aliquot syncing
=> Bug fix - DPL-1112 run creation with aliquots

lib/tasks/tol_tubes_report_view.rake
Closes #1277 
When this is deployed, I will trigger the rake task manually on each environment.  I didn't want to create a v2 when v1 still doesn't do what was intended for Alice.
- Update the way rows are joined between tables so that samples take priority over libraries.
_[Feature Branches] - Review code_
=> Make samples the source of the TOL report view results

app/models/concerns/aliquotable.rb, spec/models/concerns/aliquotable_spec.rb
This PR includes
- added used_volume, available_volume and volume_check in `aliquotable` concern
=> DPL-1069: Added volume methods and checks to support volume tracking

app/exchanges/run_csv/pacbio_sample_sheet_v1.rb, spec/exchanges/run_csv/pacbio_sample_sheet_v1_spec.rb
- sets Use Adapative Loading field to false for all wells
=> DPL-1040 - Fix for Use Adaptive Loading in new pacbio sample sheet format

.rubocop.yml, lib/tasks/create_printers.rake, spec/lib/tasks/create_printers.rake_spec.rb, spec/lib/tasks/volume_tracking.rake_spec.rb
=> DPL-1116 - create rake task for printers

.github/workflows/add_prs_to_tech_debt_project.yml
Closes https://github.com/sanger/General-Backlog-Items/issues/383
This PR includes the following:
- Adds an 'add_prs_to_tech_debt_project.yml' file, which adds Depfu-generated dependency update PRs to the 'Technical Debt' project board.
=> Y24-066 Created add_prs_to_tech_debt_project.yml to add dependency updates to  technical debt project

app/models/pacbio/library.rb, lib/tasks/update_used_aliquots_with_primary_aliquot_tags.rake, spec/lib/tasks/update_used_aliquots_with_primary_aliquot_tag.rake_spec.rb, spec/models/pacbio/library_spec.rb, spec/requests/v1/pacbio/libraries_spec.rb
=> feat: Update used aliquots data when primary aliquot is updated for a library

app/exchanges/volume_tracking/message_builder.rb, config/pipelines/pacbio.yml, spec/exchanges/volume_tracking/message_builder_spec.rb, spec/messages/emq/encoder_spec.rb, spec/messages/emq/publishing_job_spec.rb
=> Updating to serialize UUIDs properly with raw UUID values

lib/tasks/update_used_aliquots_with_primary_aliquot_tags.rake, spec/factories/pacbio/libraries.rb, spec/lib/tasks/update_used_aliquots_with_primary_aliquot_tag.rake_spec.rb
=> refactor: Add message publishing to updating tags for used_aliquots

lib/tasks/create_printers.rake, spec/lib/tasks/create_printers.rake_spec.rb
Closes https://github.com/sanger/traction-ui/issues/1788
- Added two printers ("psd-2", "aa212bc2") to rake tasks (UI change is already in prod)
=> Y24-163 - Add bulk printing for 384 labels

.gitignore, Gemfile, Gemfile.lock
-  Removes sqlite3 gem as it is no longer used
=> deps: remove unused sqlite3

app/messages/emq/publishing_job.rb, lib/tasks/push_aliquot_data_to_warehouse.rake, spec/lib/tasks/push_aliquot_data_to_warehouse.rake_spec.rb, spec/messages/emq/publishing_job_spec.rb
Closes #https://github.com/sanger/traction-service/issues/1371
- Creates a rake task to push all aliquots to the warehouse using EMQ 
=> Y24-217 push historic data to warehouse

app/models/pacbio/pool.rb, config/feature_flags.yml, spec/models/concerns/aliquotable_spec.rb, spec/models/pacbio/pool_spec.rb, spec/models/pacbio/well_spec.rb
Closes #1376 
- Removed feature flag for volume tracking: `y24_153__enable_volume_check_pacbio_pool_on_update`
=> Y24-227 - Removed feature flags for volume tracking

lib/tasks/create_tags.rake, spec/lib/tasks/create_tags.rake_spec.rb
=> chore: Add PiMmS_TruSeq_adapters_v1 tag set and tags

app/messages/emq/publishing_job.rb, spec/messages/emq/publishing_job_spec.rb
Closes #1427 
- Change the publishing job to not to throw when the AMQP connection errs.
=> Updating the code to not to throw when the EMQ is down

config/pipelines/reception.yml, spec/requests/v1/reception_spec.rb
Reverts sanger/traction-service#1437
=> Revert "Y24 318 modify message send to warehouse so that the id_sample_lims will be the sample name"

app/models/aliquot.rb, spec/models/aliquot_spec.rb
=> Fixed issue with incorrect use of hidden for sample sheet behaviour.

lib/tasks/create_tags.rake, spec/lib/tasks/create_tags.rake_spec.rb, spec/lib/tasks/ont_data.rake_spec.rb
=> Add SQK-PCB114.24 tag set and tags

app/exchanges/volume_tracking/message_builder.rb, app/resources/v1/pacbio/library_resource.rb, config/pipelines/pacbio.yml, spec/exchanges/volume_tracking/message_builder_spec.rb, spec/messages/emq/publishing_job_spec.rb, spec/requests/v1/pacbio/libraries_spec.rb
Closes #1451 
- Filter request aliquots and publish them to mlwh.
=> Publishing filtered aliquots

lib/tasks/create_tags.rake
=> Refactor tag set creation to deactivate tag sets that are no longer used

app/models/aliquot.rb, app/models/pacbio/run.rb, lib/tasks/push_aliquot_data_to_warehouse.rake, spec/lib/tasks/push_aliquot_data_to_warehouse.rake_spec.rb, spec/models/aliquot_spec.rb
=> Added requests to push_aliquot_data_to_warehouse.

config/pipelines/pacbio.yml
=> fix(pacbio): update v13_1_revio to reference v13_revio for consistency

Gemfile, Gemfile.lock
=> Add syslog gem to Gemfile and update Gemfile.lock for Ruby 3.4 compatibility

app/resources/v1/pacbio/library_batch_resource.rb, spec/requests/v1/pacbio/library_batches_spec.rb
Closes #
publish volume tracking messages when create batch libraries
- 
=> publish library volumes after library batch creation

config/pipelines/pacbio.yml, spec/messages/emq/encoder_spec.rb, spec/messages/emq/publishing_job_spec.rb
Reverts sanger/traction-service#1519
=> Revert "Y24-488 update pacbio.yml "

config/application.rb
=> bump Rails configuration defaults to version 7.2

documentation/volume-tracking/docs/explanation-of-queries.md, documentation/volume-tracking/docs/querying-mlwh.md, documentation/volume-tracking/mkdocs.yml
=> Enhance documentation for volume tracking by updating attribute descriptions and adding a new section on top-up management

app/resources/v1/shared/source_identifier_filterable.rb, spec/requests/v1/pacbio/requests_spec.rb, spec/requests/v1/shared/source_identifier_filterable_spec.rb
Closes https://github.com/sanger/traction-service/issues/1541
-  The filter_values method in source_identifier_filterable has been updated to correct condition processing and enhance record filtering logic, enabling incremental filtering based on specified conditions.
=> Y25-093 fix search for library by its source using plate barcode with well location

app/ont/ont.rb, spec/requests/v1/ont/runs_spec.rb
=> update rebasecalling options

app/models/pacbio/library.rb, app/models/pacbio/pool.rb, app/resources/v1/pacbio/library_resource.rb, app/resources/v1/pacbio/pool_resource.rb, spec/models/pacbio/library_spec.rb, spec/models/pacbio/pool_spec.rb, spec/requests/v1/pacbio/libraries_spec.rb, spec/requests/v1/pacbio/pools_spec.rb
Part of https://github.com/sanger/traction-ui/issues/2228
- Add barcode attribute to PacBio Library and Pool model via delegation to tube.
- Add barcode attribute to API resource for PacBio Library and Pool.
=> Y25-169 - Add barcode attribute to PacBio Library and Pool resources

app/models/pacbio/run.rb, app/resources/v1/pacbio/run_resource.rb, spec/models/pacbio/run_spec.rb, spec/requests/v1/pacbio/runs_spec.rb
=> Remove deprecated comments attribute and related tests from Pacbio run model and resources

app/models/reception/resource_factory.rb, app/models/sample.rb, config/pipelines/reception.yml, spec/models/reception/resource_factory_spec.rb
=> Fix mistakes in tests

.github/workflows/asset_dispatch.yml
Closes #1553 
- Migrated setup steps to use the composite actions
- Migrated the release steps to use the composite actions
- Minor improvements to syntax and structure
=> Y25-108-1 - Migrate & Improve asset_dispatch workflow

app/resources/v1/pacbio/pool_resource.rb, spec/requests/v1/pacbio/pools_spec.rb
Closes #1698
- Corrects filter to look at both the pools requests and libraries when looking for related samples.
=> Y25-573 - Fixes PacBio Pool resource sample_name filter
