sanger/traction-service

app/controllers/v1/samples_controller.rb
app/models/chip.rb
app/models/run_factory.rb
app/models/sample.rb
db/migrate/20181112145617_create_samples.rb
db/migrate/20190212110741_create_chips.rb
db/schema.rb
lib/tasks/create_dummy_runs.rake
spec/factories/chips.rb
spec/factories/samples.rb
spec/models/chip_spec.rb
spec/models/sample_factory_spec.rb
spec/models/sample_spec.rb
spec/requests/v1/chips_spec.rb

Added serial number to chip updated from barcode. 
Made chip barcode mandatory of at least length 16. 
Added study id to sample and made it required.
Added an arbitary chip barcode in run factory until we have had a chance to sort out the new run creation.
The above changes are necessary otherwise it will affect the integrity of the warehouse data.
TODO: Update traction-ui to pull study uuid and sample uuid.

Changes necessary for updating warehouse

---

app/messages/messages/message.rb
app/models/pacbio/library_factory.rb
app/models/pacbio/request_library.rb
app/models/pacbio/well_library_factory.rb
spec/factories/pacbio/request_library.rb
spec/models/pacbio/library_factory_spec.rb
spec/models/pacbio/library_spec.rb
spec/models/pacbio/request_library_spec.rb
spec/models/pacbio/well_library_factory_spec.rb
spec/pipelines/pacbio/message_spec.rb
spec/requests/v1/pacbio/wells/libraries_spec.rb

Because we are not doing multiplexing at the moment I have not added checks to ensure that all of the requests in a library have tags if there is more than one request.

Added the ability to add a request to pacbio library with no tags.

---

.rubocop.yml
config/pipelines.yml

BUG - couldnt create pacbio run
This was because after creation, a message is send to the mlwh
Which gets the message config from the pipelines.yml
Recently with rails 6 upgrade, the way of loading the config had changed
to have the uat << default pipelines.yml load the config
Also has to disable rubocop check UniqueValidationWithoutIndex
which is current failing a different depfu update **UPDATE** not needed on travis

Added BUG fix for issue #376 pipelines config uat misssing

---

app/models/ont/plate_factory.rb
app/models/ont/request_factory.rb
app/models/ont/well_factory.rb
app/services/tag_service.rb
db/migrate/20200506214419_add_multi_column_index_to_samples.rb
db/schema.rb
spec/models/ont/plate_factory_spec.rb
spec/models/ont/request_factory_spec.rb
spec/models/ont/well_factory_spec.rb

I've partially done this, but I've put it down due to time boxing.  The requests do process faster here, but there's still an outstanding issue I haven't been able to resolve AND there are more issues looking at the SQL logs.  The main outstanding issue in this branch is that I wasn't able to get the entities created by the Request Factory to only validate once in a normal workflow.  This is because the Ont::Request and the Sample are set to autosave the Request when their relationships are updated.  And the Request is set to autosave the Ont::Request and Sample when it's relationships are updated.  This is good, but the save causes another validation.  I tried removing the autosave from the relationships but that: a) causes issues in Pacbio and Saphyr which rely on this autosave and b) …

GPL-426 Optimise plate creation

---

app/graphql/mutations/create_plate_with_covid_samples_mutation.rb
app/graphql/types/mutation_types.rb
spec/requests/v2/plates_spec.rb

Part of #362 
* Rename the mutation method to be specific to Covid samples.

Update name of plate mutation to match Covid workflow

---

app/models/ont/flowcell.rb
app/models/ont/run_factory.rb
app/pipelines/pipelines/constants_accessor.rb
config/pipelines.yml
spec/models/ont/flowcell_spec.rb
spec/models/ont/library_factory_spec.rb
spec/models/ont/run_factory_spec.rb
spec/pipelines/constants_accessor_spec.rb

* Add the run factory
* Ensure it only validates it's created entities once, and validation can be skipped altogether

Gpl 387 run factory

---

app/models/ont/request_factory.rb
app/pipelines/pipelines/constants_accessor.rb
config/pipelines.yml
spec/models/ont/request_factory_spec.rb
spec/pipelines/constants_accessor_spec.rb

* Re-add the constants accessor
* Allow getting the Covid sample pcr_tag_set_name from the constants

Config request tag set name

---

app/models/ont/library.rb
spec/factories/ont/libraries.rb
spec/models/ont/library_spec.rb
spec/requests/v2/ont/libraries_spec.rb

* Add a uniqueness to library names
* With the current implementation ensures that only one library can exist from the pooling of a single plate

Library name uniqueness

---

README.md
config/pipelines.yml
lib/tasks/ont_data.rake

Closes #
* modify rake task for creating ont runs so that you can create plates and libraries to make it easier to test with the ui
* added a count so you can specify the number of plates and runs you would like to create
* modified so that you can rerun it without getting any errors. It will take the last plate and set the barcode based on that.
* rubocopped so split up the task a bit.

Modify ont rake task

---

config/pipelines.yml
spec/pipelines/ont/message_spec.rb

Closes https://github.com/sanger/unified_warehouse/issues/96
* Make empty string values pass as null now that the database can accept a null value for these columns.

GPL-418: Remove pipeline keys we won't use for Covid19 samples

---

app/graphql/mutations/base_covid_run_mutation.rb
config/pipelines.yml

Closes #
* Very significantly improve the performance of lookups of the run.  Turns thousands of database requests for message preparation into only 7 requests.
* The run by ID
* The associated flowcells for the run
* The associated libraries for the flowcells
* The associated requests for the libraries
* The associated tag_taggables for the requests
* The associated tags for the tag_taggables
* The associated tag set for the tags

Improve run lookup performance

---

app/graphql/mutations/base_covid_run_mutation.rb
app/graphql/mutations/create_covid_libraries_mutation.rb
app/graphql/mutations/create_covid_run_mutation.rb
app/graphql/mutations/create_plate_with_covid_samples_mutation.rb
app/graphql/mutations/update_covid_run_mutation.rb
app/graphql/types/query_types.rb
app/models/container_material.rb
app/models/ont/flowcell.rb
app/models/ont/library.rb
app/models/ont/request.rb
app/models/ont/run.rb
app/models/plate.rb
app/models/tag.rb
app/models/tube.rb
app/models/well.rb
spec/models/container_material_spec.rb
spec/models/ont/flowcell_spec.rb
spec/models/ont/library_spec.rb
spec/models/ont/request_spec.rb
spec/models/ont/run_spec.rb
spec/models/plate_spec.rb
spec/models/tag_spec.rb
spec/models/tube_spec.rb
spec/models/well_spec.rb

Closes #355 
* Give each active record in the Ont pipeline a `includes_args` class method which returns a list of arguments to call in the `includes` class method.
* Allow specifying arguments to remove from this list to avoid circular dependencies (e.g. when drilling down from a run to a flowcell, you don't want the flowcell's args to again include the run)
* Where needed add a `resolved_query` method that returns a queryable object with all dependencies resolved
* Use the `resolved_query` method for GraphQL queries and mutations

Gpl 445 performance improvements

---

app/graphql/types/outputs/ont/run_type.rb
app/views/graphql/object/run/index.html
lib/graphql_schema.graphql
lib/graphql_schema.json
spec/requests/v2/ont/runs_spec.rb

Links to https://github.com/sanger/traction-ui/issues/445
* Expose a run's experiment name in GraphQL queries

Allow fetching a run's experiment name

---

app/models/pacbio/library_factory.rb
spec/models/pacbio/library_factory_spec.rb

* Updated library factory function to check for nil cost_code
* Added supporting test
* ...

Fix for libraries created without costcode

---

app/models/concerns/sample_sheet.rb
spec/models/concerns/sample_sheet_spec.rb

Automation parameters now checks if pre-extension time is 0, if so is blank
Closes #
*
*
* ...

Change to automation parameters in sample sheet

---

app/resources/v1/pacbio/pool_resource.rb
spec/requests/v1/pacbio/pools_spec.rb

Closes #
* The timestamp needs to be formatted so it is easy to understand for the users and so that it can be filtered correctly
*
* ...

updated pool resource to return a formatted created_at timestamp

---

app/controllers/v1/pacbio/libraries_controller.rb
app/models/pacbio/library.rb
config/routes.rb
lib/tasks/pacbio_data.rake
spec/models/pacbio/library_spec.rb
spec/requests/v1/pacbio/libraries_spec.rb

Closes #
Service work for https://github.com/sanger/traction-ui/pull/671
* Removed ability to create library (single plexed pool) from library resource
* Added tube relationship to library via its parent pool
* ...

Service work for - Bug library creation from sample

---

app/controllers/v1/pacbio/plates_controller.rb
app/models/pacbio/plate_creator.rb
spec/models/pacbio/plate_creator_spec.rb
spec/requests/v1/pacbio/plates_spec.rb

This isn't strictly necessary for dpl-273 but without it we were receiving empty error messages.
This also tweaks the error formatting to be compliant with json-api standards.

Improve plate creation error handling

---

.rubocop_todo.yml
app/models/concerns/nested_validation.rb
app/models/pacbio/library.rb
app/models/pacbio/pool.rb
app/models/pacbio/well_factory.rb
app/resources/v1/pacbio/library_resource.rb
app/resources/v1/pacbio/pool_resource.rb
app/resources/v1/shared/run_suitability.rb
spec/factories/pacbio/libraries.rb
spec/models/pacbio/library_factory_spec.rb
spec/models/pacbio/library_spec.rb
spec/models/pacbio/pool_spec.rb
spec/models/pacbio/well_factory_spec.rb
spec/requests/v1/pacbio/libraries_spec.rb
spec/requests/v1/pacbio/pools_spec.rb

Closes #752
* Removes validation of presence of volume, concentration, insert size on library creation
* Adds run_creation validation scope which enforces this instead
* Refines validation on volume, concentration, insert size
* Validates libraries are valid for run creation on run creation
* Adds field describing suitability for run creation to API

Issue752/dpl 396 as a team lead {james} i would like to create libraries without the qc data so we can print barcodes in the lab and freeze them

---

app/models/qc_results_upload_factory.rb
spec/models/qc_results_upload_factory_spec.rb

* Changed a method name to make it more generic
Non-blocking relationship with: https://github.com/sanger/traction-ui/pull/1038

Make method name generic

---

config/pacbio_smrt_link_versions.yml

Closes #
Use default block for training in config/pacbio_smrt_link_versions.yml

Rake task fix for smrt link versions on training

---

app/pipelines/pipelines.rb

Fixed issue where QcResult pipeline wasn't being loaded in the pipelines config
This was introduced when I changed the way pipelines were loaded in #888

Bug fix - QC Result pipeline was not being loaded correctly.

---

app/resources/v1/pacbio/plate_resource.rb
app/resources/v1/pacbio/pool_resource.rb
app/resources/v1/pacbio/request_resource.rb
lib/tasks/pacbio_data.rake
lib/tasks/reception_generator.rb
spec/requests/v1/pacbio/plates_spec.rb
spec/requests/v1/pacbio/pools_spec.rb
spec/requests/v1/pacbio/requests_spec.rb
spec/requests/v1/pacbio/runs_spec.rb
spec/requests/v1/pacbio/tubes_spec.rb

* Updated pacbio resources missing pagination. (plates, tubes and requests)
* Updated reception generator to handle iteration errors for tube creation
This PR is coupled with: https://github.com/sanger/traction-ui/pull/1110

DPL-705 Prevent pacbio pulling back all records

---

app/resources/v1/pacbio/library_resource.rb
spec/requests/v1/pacbio/libraries_spec.rb

* Added ability to wildcard search by barcode for pacbio library resource
Note:
Im not the biggest fan of having to pass a 'wildcard' string with the search value but jsonapi-resources doesn't allow any extra values to be passed in the filters.

DPL-725 - Added ability to wildcard search by barcode for pacbio library resource

---

lib/tasks/pacbio_data.rake
spec/lib/tasks_spec.rb

- Removes `v10` seeding data
- Adds `v11` seeding data
- Wells incomplete and showing red (as in v`10`)
- Adds `v12_revio` seeding data
- Wells complete and showing green
- 3 x 1-plate runs
- 3 x 2-plate runs

Update seeding data for v11 and v12_revio

---

app/resources/v1/pacbio/smrt_link_version_resource.rb
spec/requests/v1/pacbio/smrt_link_versions_spec.rb

Pass through all SMRT Link Versions, not just the active ones
- pass through the active attribute so that the UI can decide what to do with it
- allows a bug to be fixed where the UI wasn't rendering old runs properly
- checked as well as I could and seems to be a safe change
See comment https://github.com/sanger/traction-ui/issues/1300#issuecomment-1748946591 and screenshots on story https://github.com/sanger/traction-ui/issues/1300#issuecomment-1749062904
Closes #
- 

DPL-871 View old runs

---

app/resources/v1/ont/run_resource.rb
config/initializers/jsonapi_resources.rb
spec/requests/v1/ont/runs_spec.rb

Required for DPL-888 (UI add page by page pagination)
- json api resources return page count in response meta
- Adds experiment_name and state filters to ONT run resource

DPL-888 - Add page by page pagination

---

app/resources/v1/pacbio/library_pool_resource.rb
app/resources/v1/pacbio/library_resource.rb
app/resources/v1/pacbio/pool_resource.rb
spec/factories/pacbio/libraries.rb
spec/lib/tasks/migrate_pacbio_aliquot_data.rake_spec.rb
spec/requests/v1/pacbio/libraries_spec.rb

- Adds PacBio LibraryPoolResource. This is so the Pacbio PoolResource can access all PacBio Libraries.
- Updates PacBio LibraryResource to only return records without pools (new libraries).
One alternative approach is to this is to create a separate endpoint for the libraries without pools. I don't feel strongly about either approach as they both have their own issues.
Another approach is to filter out libraries with pools in the front end. However this will break pagination completely because the service and UI will be out of sync. e.g. service sends 25 libraries (some with pools), Ui only shows libraries without pools e.g. 10 libraries.
&nbsp; &nbsp; \- _Check story numbers …

DPL-1066 - Modifies the pacbio library endpoint to only return libraries without pools.

---

db/migrate/20240227103930_change_estimate_of_gb_required_to_string.rb
db/schema.rb
spec/factories/pacbio/requests.rb
spec/models/pacbio/request_spec.rb

The down method will only be successful if the data in the column is still all integers. If values have been populated with non-integers, the migration cannot be rolled back without altering the database first.
Closes #1225 
- Create a migration to change the estimate_of_gb_required to a string.
- Ensuree the migration could be rolled back so long as the data is still all integers.
_[Feature Branches] - Review code_

DPL-1110: Change the estimate_of_gb_required column to a string

---

lib/tasks/pacbio_data.rake

- Changes sequencing kit box barcode generation to include random date string to reduce possibility of duplicate barcodes in data generation.
This change is required because there is validation that a sequencing kit box barcode is not reused on multiple plates. This validation sometimes gets tripped in the pacbio data rake spec because there is a low chance of two plates being randomly generated with the same sequencing kit box barcode and causing the spec to fail. This PR aims to make that chance much lower while maintaining barcode validity.

Fix for intermittent pacbio data rake task spec failures

---

app/models/pacbio/well.rb
app/resources/v1/pacbio/aliquot_resource.rb
app/resources/v1/pacbio/runs/aliquot_resource.rb
app/resources/v1/pacbio/runs/request_resource.rb
app/resources/v1/pacbio/runs/tag_resource.rb
app/resources/v1/pacbio/runs/tube_resource.rb
app/resources/v1/pacbio/runs/well_resource.rb
config/feature_flags.yml
lib/tasks/migrate_pacbio_aliquot_data.rake
lib/tasks/pacbio_data.rake
spec/factories/pacbio/wells.rb
spec/lib/tasks/migrate_pacbio_aliquot_data.rake_spec.rb
spec/models/pacbio/well_spec.rb
spec/requests/v1/pacbio/runs/wells_spec.rb
spec/requests/v1/pacbio/runs_spec.rb

Closes #1226 
- Overloads well pool_ids and library_ids method to also handle used_aliquots creation and deletion

DPL-1112 - Handle used_aliquots for run creation

---

app/models/aliquot.rb
app/models/pacbio/library.rb
spec/models/aliquot_spec.rb
spec/models/pacbio/library_spec.rb

This PR includes
Added checks for  associated pools in a library before destroying a library

DPL-993 - Disallow deletion of libraries that are part of pools 

---

app/validators/tag_validator.rb
spec/models/ont/pool_spec.rb

TagValidator is a shared class between PacBio and ONT. With the introduction of the aliquot work this has broken tag validation in ONT which does not have aliquots. 
- Updates TagValidator to only validate via used_aliquots if the record can respond to used_aliquots.

fix(ont-pools): fixes tag validation to go via libraries

---

app/models/concerns/pipelineable.rb
app/models/reception/resource_factory.rb
app/ont/ont.rb
app/pacbio/pacbio.rb
app/resources/v1/reception_resource.rb
app/saphyr/saphyr.rb
spec/requests/v1/reception_spec.rb

Closes #1255 
- Reception message accepts data for library attributes against tubes.
- When these are missing, the result is the same as before.
- When these are there and valid, the library is created for the request.
- When these are there but invalid, the service gives a 422 response.
_[Feature Branches] - Review code_

Y24-018: Tube reception accepts library creation attributes

---

app/models/concerns/aliquotable.rb
app/models/pacbio/library.rb
spec/models/concerns/aliquotable_spec.rb
spec/models/pacbio/library_spec.rb

This story aims to split the PRs for volume checks in the 'Aliquotable' concern from the callback hook in the 'Library' model ([PR](https://github.com/sanger/traction-service/pull/1288)) 
This separation enables independent deployment of this story, whereas changes to the Library model necessitate more extensive testing.

DPL 1070 - aliquotable volume check

---

lib/tasks/volume_tracking.rake
spec/lib/tasks/volume_tracking.rake_spec.rb

Closes #1293 
- Adds volume_tracking rake file
- Adds clear_well_aliquot_volume rake task to clear volume and conc in aliquots used by wells to ensure old arbitrary data doesn't violate volume checks.

Y24-059 - Fix data that violates volume checks

---

app/models/pacbio/run.rb
spec/models/pacbio/run_spec.rb

Closes #627 
- When a run is created, the barcode will have the format: "BARCODE CONCENTRATION". The same will happen when a run is updated as long as the comment is empty.

Y24-073 - Populate PacBio run comments with pool barcode + concentration

---

lib/tasks/create_printers.rake
spec/lib/tasks/create_printers.rake_spec.rb

This commit adds new printers for tubes and plates in the `create_printers.rake` file. Two new printers, `aa309bc2` and `aa303bc`, are created with the labware types `plate96`. This change ensures that the printers are properly created and available for use.
Closes #
- 

chore: Add new printers for plates

---

app/models/ont/pool.rb
app/models/reception.rb
app/models/reception/resource_factory.rb
app/models/reception/unknown_library_type.rb
app/ont/ont.rb
app/resources/v1/reception_resource.rb
codecov.yml
spec/lib/tasks/volume_tracking.rake_spec.rb
spec/models/ont/pool_spec.rb
spec/models/reception/resource_factory_spec.rb
spec/requests/v1/reception_spec.rb

Closes #1339
- Adds pool_attributes to reception api
- Enables ONT pool tube barcode to be overridden
- Enables ONT pools to be created via the reception
This PR's code can be reviewed but it is reliant on [Y24-126-2](https://github.com/sanger/traction-ui/issues/1747) being completed for manual end to end testing.

Y24-126-1 - Support automatic pool creation in reception

---

app/models/concerns/aliquotable.rb
app/models/pacbio/pool.rb
app/models/pacbio/well.rb
app/resources/v1/pacbio/pool_resource.rb
config/feature_flags.yml
lib/tasks/pacbio_data.rake
spec/factories/pacbio/pool.rb
spec/models/concerns/aliquotable_spec.rb
spec/models/pacbio/pool_spec.rb
spec/models/pacbio/well_spec.rb

Closes #1348 
- A feature flagged change that validates `available_volume` when updating PacBio pools
- The validation of available volume when editing a PacBio pool is feature flagged here
This PR leaves out adding attributes to the pool resource. When working on https://github.com/sanger/traction-ui/issues/1784, these will need to be added so that validation on the UI happens when adding a pool to a run (from what I can see, that validation already partially exists)

Y24-153 - Added volume check to PacBio pools

---

lib/tasks/create_printers.rake
spec/lib/tasks/create_printers.rake_spec.rb

Closes https://github.com/sanger/traction-ui/issues/1788
- Added another printer ("aa312bc2") to rake tasks (UI change is already in prod)

Y24-163 - [2] Add bulk printing for 384 labels

---

app/exchanges/volume_tracking/message_builder.rb
app/messages/emq/publishing_job.rb
app/models/pacbio/run.rb
app/resources/v1/pacbio/run_resource.rb
spec/exchanges/volume_tracking/message_builder_spec.rb
spec/messages/emq/publisher_spec.rb
spec/models/pacbio/run_spec.rb
spec/requests/v1/pacbio/runs_spec.rb

Closes https://github.com/sanger/traction-service/issues/1206
- Publish message to EMQ for all library aliquots when a run is created or updated

DPL-1074 sent library volume to warehouse while creating or updating a sequencing run

---

config/pipelines/reception.yml
spec/requests/v1/reception_spec.rb

Closes #1349 
- Stop sending the retention instruction to warehouse

Removing retention instruction from warehouse message

---

app/exchanges/volume_tracking/message_builder.rb
app/resources/v1/pacbio/library_resource.rb
spec/exchanges/volume_tracking/message_builder_spec.rb
spec/messages/emq/publisher_spec.rb
spec/requests/v1/pacbio/libraries_spec.rb

Closes #1202
- Sending volume tracking message when libraries are created and/or updated.

As a long read user I would like the volume to be sent to the warehouse so I can track library volumes and enable top-up management

---

app/models/pacbio/run.rb
spec/models/pacbio/run_spec.rb

Closes https://github.com/sanger/traction-service/issues/1408
- The aliquots_to_publish_on_run method in the run model has been modified to include aliquots from all libraries directly added to all run wells.

Y24-274 fix to publish data to include aliquots from all libraries in a run

---

config/pipelines/reception.yml
spec/requests/v1/reception_spec.rb

Closes https://github.com/sanger/traction-service/issues/1430
- The id_sample_lims field in message send to warehouse is changed to sample name instead of traction sample ids

Y24 318 modify message send to warehouse so that the id_sample_lims will be the sample name

---

app/models/aliquot.rb

Y24-320 - modify sample sheet behaviour so that Revio sample sheets behave as untagged when the behaviour is set to hidden

---

config/pipelines/reception.yml
spec/requests/v1/reception_spec.rb

Closes https://github.com/sanger/traction-service/issues/1430
- The id_sample_lims field in message send to warehouse is changed to sample name instead of traction sample ids

Y24-318 modify warehouse message with sample name

---

.github/workflows/asset_dispatch.yml
.github/workflows/automated_release_and_build.yml
.github/workflows/check_release_version.yml
.github/workflows/generate_pages.yml
.github/workflows/ruby.yml

Closes https://github.com/sanger/General-Backlog-Items/issues/433
- Bumped `checkout` dependency to v4.

Y24-244 - Update checkout dependency to v4

---

app/exchanges/volume_tracking/message_builder.rb
spec/exchanges/volume_tracking/message_builder_spec.rb

Closes #1457
- Updates volume tracking message builder to send used_by_well_barcode in the format <run_name>:<well_position>
Wondering if the plate number is still useful?

Y24-403 - Send run name with well library aliquots

---

app/resources/v1/pacbio/request_resource.rb
app/resources/v1/pacbio/tag_set_resource.rb
spec/requests/v1/pacbio/requests_spec.rb
spec/requests/v1/pacbio/tag_sets_spec.rb

Closes https://github.com/sanger/traction-service/issues/1489
-Enhanced the `filter :source_identifier` in request_resource to support multiple source identifiers instead of just one.
-Added filter by name option to pacbio tagsets resource

Y24-412 - request end point filter update with multiple source identifiers

---

app/models/pacbio/library.rb
app/models/pacbio/pool.rb
config/bunny.yml.example
spec/requests/v1/pacbio/libraries_spec.rb
spec/requests/v1/pacbio/pools_spec.rb

- The UI can send primary aliquots of existing pools/libraries without their ids. This change prevents the aliquot being deleted and recreated in that case.

fix(primary-aliquot): fixes bug where pool and library primary aliquots without ids caused the aliquots to be remade

---

app/exchanges/run_csv/pacbio_sample_sheet.rb
app/exchanges/run_csv/pacbio_sample_sheet_v25.rb
app/models/pacbio/run.rb
app/resources/v1/pacbio/run_resource.rb
app/resources/v1/pacbio/runs/well_resource.rb
app/resources/v1/pacbio/smrt_link_version_resource.rb
app/resources/v1/pacbio/well_resource.rb
app/validators/smrt_link_options_validator.rb
app/validators/use_adaptive_loading_validator.rb
config/pacbio_smrt_link_versions.yml
config/pipelines/pacbio.yml
spec/exchanges/run_csv/pacbio_sample_sheet_spec.rb
spec/exchanges/run_csv/pacbio_sample_sheet_v25_spec.rb
spec/factories/pacbio/wells.rb
spec/models/pacbio/run_spec.rb
spec/models/pacbio/well_spec.rb
spec/requests/v1/pacbio/runs_spec.rb
spec/validators/smrt_link_options_validator_spec.rb
spec/validators/use_adaptive_loading_validator_spec.rb

Closes #1510 
- Adds v25_1_revio SMRTLink option.
- Adds pacbio_sample_sheet_v25 to handle well settings uniquely for the v25_1_revio sample sheets.
- Adds use_adaptive_loading and full_resolution_base_qual smrt link options.
- Adds custom smrt link option validator to handle use_adaptive_loading constraint to be the same for all wells in a run.
- Adds and exposes 'adaptive_loading' and 'sequencing_kit_box_barcodes' PacBio Run helper methods to the API.
Not sure if the custom smrt link option validator is the best option or not. The requirement is to ensure all v13 > revio runs using use_adaptive_loading have a consistent value across the run - all True or all False. So this validation is a mix of instrument type, smrt link option, run and well validation.

Y24-518 - SMRTLink v25.1 Revio support

---

config/pipelines/pacbio.yml
spec/messages/emq/encoder_spec.rb
spec/messages/emq/publishing_job_spec.rb

Closes 
- Update pacbio.yml to use updated_at instead of created_at for the recordedAt value. This will allow unified_warehouse to determine the latest record, thereby creating an audit trail of records if any field value changes.

Y24-488 update pacbio.yml 

---

app/exchanges/run_csv/pacbio_sample_sheet.rb
app/exchanges/run_csv/pacbio_sample_sheet_v25.rb
app/models/aliquot.rb
app/models/pacbio/well.rb
spec/exchanges/run_csv/pacbio_sample_sheet_v25_spec.rb
spec/models/aliquot_spec.rb
spec/models/pacbio/well_spec.rb

Closes https://github.com/sanger/traction-service/issues/1544
- Update bio_sample_name by replacing colons with hyphens for CSV upload in SmrtLink V25.

Y25-097 replace colon with hyphen for sample upload csv for smart link v25

---

.rubocop.yml
app/exchanges/run_csv/pacbio_sample_sheet.rb
app/models/pacbio/run.rb
app/resources/v1/pacbio/run_resource.rb
config/pipelines/pacbio.yml
db/migrate/20250319151746_rename_pacbio_run_comments_to_barcodes_and_concentrations.rb
db/schema.rb
spec/exchanges/run_csv/pacbio_sample_sheet_legacy_spec.rb
spec/exchanges/run_csv/pacbio_sample_sheet_spec.rb
spec/exchanges/run_csv/pacbio_sample_sheet_v25_spec.rb
spec/factories/pacbio/runs.rb
spec/models/pacbio/run_spec.rb
spec/requests/v1/pacbio/runs_spec.rb

Closes #
- 
Previously we were inserting a space at the start of the barcodes and concentrations. I see no need to continue doing this but at the same time see no need to modify existing records.

Y25-080 - rename comments to barcodes_and_concentrations in Pacbio run model and update related references

---

app/models/ont/request.rb
app/models/pacbio/request.rb
app/resources/v1/ont/request_resource.rb
app/resources/v1/pacbio/request_resource.rb
app/resources/v1/reception_resource.rb
spec/requests/v1/ont/requests_spec.rb
spec/requests/v1/pacbio/plates_spec.rb
spec/requests/v1/pacbio/requests_spec.rb

Closes https://github.com/sanger/traction-ui/issues/2234
This pull request introduces support for handling the `sample_retention_instruction` attribute across both ONT and PacBio requests. The changes include updates to models, API resources, and test cases to ensure the new attribute is properly integrated and validated

Y25-175 retention instruction in request attributes

---

app/models/pacbio/well.rb
spec/exchanges/run_csv/pacbio_sample_sheet_spec.rb
spec/models/pacbio/well_spec.rb

Closes N/A
- Instead of returning true or false depending on whether or not aliquots are tagged, the method will now return nil if not tagged, or true or false depending on whether or not the tag set linked in asymmetric.

refactor: modified the behaviour of "same barcodes on both ends of sequence"

---

Gemfile
Gemfile.lock
config/initializers/jsonapi_resources.rb

Closes #
- Use sanger-jsonapi-resources version 0.2.1 .
- Remove the patch for the missing Rack symbol.

Y25-319 - [PR][Traction] Use sanger-jsonapi-resources version 0.2.1

---

lib/tasks/create_tags.rake
spec/lib/tasks/create_tags.rake_spec.rb
spec/lib/tasks/ont_data.rake_spec.rb

Closes #https://github.com/sanger/sequencescape/issues/5241
This tag set will also need manual addition in sequencescape.
- Adds SQK-RPB tag set
Tags taken from provided fasta file and https://nanoporetech.com/document/rapid-sequencing-dna-v14-pcr-barcoding-sqk-rpb114-24#:~:text=to%20reagent%20stability.-,Rapid%20Barcode%20Primers,-Component

Y25-570 - adds ONT SQK-RPB tag set
